version: '3'
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    volumes: 
    - ./app
  redis-container:
    image: "redis:alpine"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./db/docker-entrypoint-initdb.d/:ro
    
  tests:
    build: .
    volumes:
      - ./db/docker-entrypoint-initdb.d/:ro
      - ./app
    command: ["pytest", "./app/test/test.py"]
